baseURL = "https://overto.eu/"
languageCode = "en-ie"
title = "Over to you"
theme = "kiera"

pygmentsCodeFences = true

[author]
  name = "Oisín"
  github = "DestyNova"

[[menu.main]]
  identifier = "music"
  name = "Music"
  url = "/categories/music"

[[menu.main]]
  identifier = "software"
  name = "Software"
  url = "/software"
