baseURL = "https://overto.eu/"
languageCode = "en-ie"
title = "Over to you"

# Use my fork to fix broken dark mode
theme =  ["github.com/chollinger93/ink-free"]

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"

cloudinary_base_url="https://res.cloudinary.com/destynova/image/upload"

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

[params]
	mode = "dark"
	toc = true
	wpm = 200
  maxTags = 20

[author]
  name = "Oisín"
  github = "DestyNova"

[[menu.main]]
  identifier = "tech"
  name = "Tech"
  url = "/tags/tech"

[[menu.main]]
  identifier = "music"
  name = "Music"
  url = "/tags/music"

[[menu.main]]
  identifier = "learning"
  name = "Learning"
  url = "/pages/learning"

[[menu.main]]
  identifier = "software"
  name = "Software"
  url = "/pages/software"
