baseURL = "https://overto.eu/"
languageCode = "en-ie"
title = "Over to you"
theme = "kiera"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"

[author]
  name = "Oisín"
  github = "DestyNova"

[[menu.main]]
  identifier = "tech"
  name = "Tech"
  url = "/categories/tech"

[[menu.main]]
  identifier = "music"
  name = "Music"
  url = "/categories/music"

[[menu.main]]
  identifier = "software"
  name = "Software"
  url = "/software"
