baseURL = "https://overto.eu/"
languageCode = "en-ie"
title = "Over to you"

theme =  ["github.com/chollinger93/ink-free"]

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"

cloudinary_base_url="https://res.cloudinary.com/destynova/image/upload"

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']

[params]
	mode = "dark"
	toc = true
	wpm = 200
  maxTags = 20

[author]
  name = "Oisín"
  github = "DestyNova"

[[menus.main]]
  identifier = "learning"
  name = "Learning"
  url = "/pages/learning"

[[menus.main]]
  identifier = "languages"
  name = "Programming languages"
  url = "/pages/languages"

[[menus.main]]
  identifier = "startups"
  name = "Startups"
  url = "/pages/startups"

[[menus.main]]
  identifier = "software"
  name = "Software"
  url = "/pages/software"

[[menus.main]]
  identifier = "about-me"
  name = "About me"
  url = "/pages/about-me"

[[menus.tags]]
  identifier = "tech"
  name = "Tech"
  url = "/tags/tech"

[[menus.tags]]
  identifier = "music"
  name = "Music"
  url = "/tags/music"

